version: '3.3'

services:
    postgres:
        image: "postgres:13" 
        restart: always
        ports:
            - 5433:5432
        env_file:
            - .env
        volumes:
            - database-data:/var/lib/postgresql/data/ # persists data even if container shuts down
    
    redis:
        image: 'redis:alpine'
        restart: always
        ports:
            - 6379:6379
        env_file:
            - .env
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
    database-data:
        driver: local
    redis-data: